### ISSUE TITLE
Following silently crash

### ISSUE THREAD

**Issue by buxx** [buxx/rolling#36]
```
2020-12-08 19:14:31,524|server|ERROR: ("Could not cast field discreetly: invalid literal for int() with base 10: 'True'", {'#': "Could not cast field discreetly: invalid literal for int() with base 10: 'True'"})
Traceback (most recent call last):
  File "/home/bux/rolling/venv/lib/python3.7/site-packages/hapic/ext/aiohttp/context.py", line 108, in error_middleware
    response = await handler(request)
  File "/home/bux/rolling/venv/lib/python3.7/site-packages/aiohttp/web_urldispatcher.py", line 158, in handler_wrapper
    return await result
  File "/home/bux/rolling/venv/lib/python3.7/site-packages/hapic/decorator.py", line 455, in wrapper
    response = await self._execute_wrapped_function(func, args, kwargs)
  File "/home/bux/rolling/venv/lib/python3.7/site-packages/hapic/decorator.py", line 462, in _execute_wrapped_function
    return await func(*func_args, **func_kwargs)
  File "/home/bux/rolling/venv/lib/python3.7/site-packages/hapic/decorator.py", line 310, in wrapper
    response = await self._execute_wrapped_function(func, args, kwargs)
  File "/home/bux/rolling/rolling/server/controller/character.py", line 1463, in with_character_action
    input_ = action.input_model_serializer.load(dict(request.query))
  File "serpyco/serializer.pyx", line 346, in serpyco.serializer.Serializer.load
  File "serpyco/serializer.pyx", line 371, in serpyco.serializer.Serializer.load
  File "serpyco/serializer.pyx", line 84, in serpyco.serializer.cast_fields
serpyco.exception.ValidationError: ("Could not cast field discreetly: invalid literal for int() with base 10: 'True'", {'#': "Could not cast field discreetly: invalid literal for int() with base 10: 'True'"})
2020-12-08 19:14:31,537|server|INFO: 86.77.185.185 [08/Dec/2020:19:14:31 +0000] "POST /character/ade13fba2d34484ea187bd7ef02e954a/with-character-action/FOLLOW_CHARACTER/de5b4433473645fdbd117fe67f448399/FOLLOW_CHARACTER?discreetly=True HTTP/1.1" 500 314 "-" "-"
```

**Comment by buxx** [comment]
fixed
